/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "bBack": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bDown": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bExit": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bInfo": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bLeft": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bLeft1": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1 },
    "bLeft2": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1 },
    "bLeft3": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1, "text": "Guide" },
    "bLeft4": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1, "text": "Source" },
    "bLeft5": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1 },
    "bLeft8": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1, "text": "CH-" },
    "bLeft9": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 1 },
    "bList": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bMid1": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 1 },
    "bMid2": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 1 },
    "bMid3": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 1, "text": "3D" },
    "bMid4": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 1 },
    "bMid9": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 1 },
    "bOk": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bOptions": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bPower": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bRight": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "bRight1": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5 },
    "bRight2": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5 },
    "bRight3": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5, "text": "Ambilight" },
    "bRight4": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5, "text": "Format" },
    "bRight5": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5 },
    "bRight8": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5, "text": "CH+" },
    "bRight9": { "creationFunction": "CreateButton", "leftImageWidth": 1, "rightImageWidth": 5 },
    "bUp": { "creationFunction": "CreateButton", "leftImageWidth": 5, "rightImageWidth": 5 },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "rectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 }
};



